apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  DB_HOST: postgres.database.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_SCHEMA: dev_schema
  SPRING_PROFILES_ACTIVE: dev
  ENVIRONMENT: dev
  VITE_API_URL: ""
  VITE_ENVIRONMENT: development