apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-uat
  namespace: argocd
spec:
  project: app-kubernetes-ci-cd
  source:
    repoURL: https://github.com/gustavomr/app-kubernetes-ci-cd
    targetRevision: main
    path: k8s/uat
  destination:
    server: https://kubernetes.default.svc
    namespace: uat
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true